### ISSUE TITLE
hpx alignment segfaults

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/inncabs#1]
export INNCABS_LAUNCH_TYPES=async
export INNCABS_MIN_OUTPUT=true
export INNCABS_REPEATS=1

/home/pagrubel/build_inncabs_hpx/g++_build/alignment/alignment -t16 --hpx:bind=balanced /home/pagrubel/hpx-inncabs/bin/input/alignment/prot.20.aa 
Segmentation fault

---

Here is version of hpx and other info from using -v:
HPX - High Performance ParalleX
A general purpose parallel C++ runtime system for distributed applications
of any scale.

Copyright (c) 2007-2015, The STE||AR Group,
http://stellar-group.org, email:hpx-users@stellar.cct.lsu.edu

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Versions:
  HPX: V0.9.11-trunk (AGAS: V3.0), Git: be2ee627b5
  Boost: V1.56.0
  Hwloc: V1.10.0

Build:
  Type: release
  Date: Jul  8 2015 23:31:19
  Platform: linux
  Compiler: GNU C++ version 4.9.1
  Standard Library: GNU libstdc++ version 20140908
  Allocator: tcmalloc

**Comment by pagrubel** [comment]
The number of hpx:threads makes no difference and neither does the binding. It also occurs with the prot.100.aa as input

**Comment by pagrubel** [comment]
@hkaiser @AntonBikineev Have either of you been able to look at this?

**Comment by AntonBikineev** [comment]
@pagrubel I'm experiencing the same problem, will look into it

**Comment by pagrubel** [comment]
@nchaimov

When I compile for the std version I get the following error:

home/pagrubel/hpx-inncabs//alignment/alignment.h: In function ‘void forward_pass(char_, char_, int, int, int_, int_, int_, int, int)’:
/home/pagrubel/hpx-inncabs//alignment/alignment.h:134:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> HH = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:134:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> HH = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:135:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> DD = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:135:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> DD = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h: In function ‘void reverse_pass(char_, char_, int, int, int_, int_, int, int, int)’:
/home/pagrubel/hpx-inncabs//alignment/alignment.h:174:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> HH = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:174:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> HH = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:175:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> DD = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:175:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> DD = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h: In function ‘int diff(int, int, int, int, int, int, int_, int_, int_, int, int, int, int)’:
/home/pagrubel/hpx-inncabs//alignment/alignment.h:218:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> HH = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:218:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> HH = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:219:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> DD = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:219:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> DD = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:220:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> RR = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:220:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> RR = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:221:33: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<int[]> SS = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                 ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:221:50: error: expected primary-expression before ‘int’
     std::unique_ptr<int[]> SS = std::make_unique<int[]>(MAX_ALN_LENGTH);
                                                  ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h: In lambda function:
/home/pagrubel/hpx-inncabs//alignment/alignment.h:415:52: error: ‘make_unique’ is not a member of ‘std’
                     std::unique_ptr<int[]> displ = std::make_unique<int[]>(2_MAX_ALN_LENGTH+1);
                                                    ^
/home/pagrubel/hpx-inncabs//alignment/alignment.h:415:69: error: expected primary-expression before ‘int’
                     std::unique_ptr<int[]> displ = std::make_unique<int[]>(2_MAX_ALN_LENGTH+1);

**Comment by nchaimov** [comment]
@pagrubel I think it may need to be built with --std=c++14 for std::make_unique to exist.

**Comment by AntonBikineev** [comment]
@nchaimov maybe just using std::vector would solve the problem

**Comment by hkaiser** [comment]
> @pagrubel I think it may need to be built with --std=c++14 for std::make_unique to exist.

You need -std=c++11 to make `std::unique_ptr` work. But I agree with @AntonBikineev that `std::vector` would work just fine.

**Comment by pagrubel** [comment]
Alignment is now working, the graph shows scaling of alignment while allocating the data on the stack for the std version and on the heap for both versions (now using tcmalloc)
[hpx_std_stack_vs_heap.pdf](https://github.com/STEllAR-GROUP/inncabs/files/46902/hpx_std_stack_vs_heap.pdf)
