### ISSUE TITLE
cannot compile with clang

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/inncabs#3]
cmake -DHPX_ROOT=~/build/hpx_buildrelease_clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DINNCABS_USE_HPX_FUTURIZED=ON \
    -DHPX_DIR=~/build/hpx_buildrelease_clang/lib/cmake/hpx \
    ~/hpx-inncabs

results in:  
below I will post the build command for hpx with clang

-- The CXX compiler identification is Clang 3.4.2
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The C compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at /home/pagrubel/hpx/cmake/HPX_Message.cmake:43 (message):
  ERROR: Compilers do not match.  In order to compile HPX application it is
  recommended to use the same compiler as you did for HPX.
  HPX_CXX_COMPILER=/usr/bin/c++, CMAKE_CXX_COMPILER=/usr/bin/clang++.  To
  disable this message set HPX_IGNORE_COMPILER_COMPATIBILITY to On.
Call Stack (most recent call first):
  /home/pagrubel/build/hpx_buildrelease/lib/cmake/HPX/HPXMacros.cmake:15 (hpx_error)
  /home/pagrubel/build/hpx_buildrelease/lib/cmake/HPX/HPXConfig.cmake:52 (hpx_check_compiler_compatibility)
  CMakeLists.txt:32 (find_package)

---

how I built hpx:

cmake -DCMAKE_INSTALL_PREFIX=~/build/hpx_buildrelease_clang                    \
      -DCMAKE_CXX_COMPILER=clang++                                    \
      -DHWLOC_ROOT=~/hwloc-1.10.1                                    \
      -DHPX_WITH_EXAMPLES=ON                                        \
      -DHPX_WITH_TESTS=ON                                           \
      -DCMAKE_BUILD_TYPE=Release                                     \
      -DHPX_WITH_THREAD_GUARD_PAGE=OFF                                    \
      -DBOOST_ROOT=/opt/boost/1.56.0-release                         \
      -DPAPI_ROOT=/opt/papi/5.4.0-release                            \
      -DHPX_WITH_PAPI=ON

**Comment by AntonBikineev** [comment]
Pat, I think you should recompile HPX with clang++ (specify CMAKE_CXX_COMPILER=clang++ when building hpx)

**Comment by pagrubel** [comment]
I’m pretty sure I did that
Pat
On Aug 14, 2015, at 2:33 PM, Anton Bikineev <notifications@github.com<mailto:notifications@github.com>> wrote:

Pat, I think you should recompile HPX with clang++ (specify CMAKE_CXX_COMPILER=clang++ when building hpx)

**Comment by pagrubel** [comment]
okay I’ll fix it sorry for the noise

On Aug 14, 2015, at 2:33 PM, Anton Bikineev <notifications@github.com<mailto:notifications@github.com>> wrote:

Pat, I think you should recompile HPX with clang++ (specify CMAKE_CXX_COMPILER=clang++ when building hpx)

**Comment by pagrubel** [comment]
fixed it for c compiler and checked that they both use /user/bin  (clang and clang++)
but get the same error

**Comment by pagrubel** [comment]
Okay here is my command for hpx:

cmake -DCMAKE_INSTALL_PREFIX=~/build/hpx_buildrelease_clang                    \
      -DCMAKE_CXX_COMPILER=clang++                                    \
      -DCMAKE_C_COMPILER=clang                                    \
      -DHWLOC_ROOT=~/hwloc-1.10.1                                    \
      -DHPX_WITH_EXAMPLES=ON                                        \
      -DHPX_WITH_TESTS=ON                                           \
      -DCMAKE_BUILD_TYPE=Release                                     \
      -DHPX_WITH_THREAD_GUARD_PAGE=OFF                                    \
      -DBOOST_ROOT=/opt/boost/1.56.0-release                         \
      -DPAPI_ROOT=/opt/papi/5.4.0-release                            \
      -DHPX_WITH_PAPI=ON             

with this output:

-- The CXX compiler identification is Clang 3.4.2
-- The C compiler identification is Clang 3.4.2
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The Fortran compiler identification is GNU
-- Enabling Fortran support
-- Native TLS is enabled.
-- Stack traces are enabled.
-- Compiling with the native toolset
-- Performing Test HPX_WITH_CXX14
-- Performing Test HPX_WITH_CXX14 - Failed
-- Performing Test HPX_WITH_CXX0Y
-- Performing Test HPX_WITH_CXX0Y - Failed
-- Performing Test HPX_WITH_CXX11
-- Performing Test HPX_WITH_CXX11 - Success
-- Performing Test HPX_WITH_CXX11_ALIAS_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_AUTO - Success
-- Performing Test HPX_WITH_CXX11_CONSTEXPR - Success
-- Performing Test HPX_WITH_CXX11_DECLTYPE - Success
-- Performing Test HPX_WITH_CXX11_DECLTYPE_N3276 - Success
-- Performing Test HPX_WITH_CXX11_DEFAULTED_FUNCTIONS - Success
-- Performing Test HPX_WITH_CXX11_DELETED_FUNCTIONS - Success
-- Performing Test HPX_WITH_CXX11_EXPLICIT_CONVERSION_OPERATORS - Success
-- Performing Test HPX_WITH_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS - Success
-- Performing Test HPX_WITH_CXX11_INLINE_NAMESPACES - Success
-- Performing Test HPX_WITH_CXX11_LAMBDAS - Success
-- Performing Test HPX_WITH_CXX11_NOEXCEPT - Success
-- Performing Test HPX_WITH_CXX11_NULLPTR - Success
-- Performing Test HPX_WITH_CXX11_RANGE_BASED_FOR - Success
-- Performing Test HPX_WITH_CXX11_RVALUE_REFERENCES - Success
-- Performing Test HPX_WITH_CXX11_SCOPED_ENUMS - Success
-- Performing Test HPX_WITH_CXX11_STATIC_ASSERT - Success
-- Performing Test HPX_WITH_CXX11_VARIADIC_MACROS - Success
-- Performing Test HPX_WITH_CXX11_VARIADIC_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_EXTENDED_FRIEND_DECLARATIONS - Success
-- Performing Test HPX_WITH_CXX11_CHRONO - Success
-- Performing Test HPX_WITH_CXX11_STD_INITIALIZER_LIST - Success
-- Performing Test HPX_WITH_CXX11_IS_FINAL - Failed
-- Performing Test HPX_WITH_CXX11_IS_NULL_POINTER - Success
-- Performing Test HPX_WITH_CXX11_UNIQUE_PTR - Success
-- Performing Test HPX_WITH_CXX11_TYPE_TRAITS - Success
-- Performing Test HPX_WITH_CXX14_CONSTEXPR - Failed
-- Performing Test HPX_WITH_CXX14_LAMBDAS - Failed
-- Performing Test HPX_WITH_CXX14_INTEGER_SEQUENCE - Failed
-- Performing Test HPX_WITH_CXX14_RESULT_OF_SFINAE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WALL
-- Performing Test HPX_WITH_CXX_FLAG_WALL - Success
-- Performing Test HPX_WITH_C_FLAG_WALL
-- Performing Test HPX_WITH_C_FLAG_WALL - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WALL
-- Performing Test HPX_WITH_Fortran_FLAG_WALL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WEXTRA
-- Performing Test HPX_WITH_CXX_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_C_FLAG_WEXTRA
-- Performing Test HPX_WITH_C_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WEXTRA
-- Performing Test HPX_WITH_Fortran_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_C_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language C.
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language Fortran.
-- Performing Test HPX_WITH_CXX_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_CXX_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_C_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_C_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SIGN_PROMO
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SIGN_PROMO - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_ATTRIBUTES
-- Performing Test HPX_WITH_CXX_FLAG_WNO_ATTRIBUTES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_CAST_ALIGN
-- Performing Test HPX_WITH_CXX_FLAG_WNO_CAST_ALIGN - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_PARAMETER
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_PARAMETER - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_IGNORED_QUALIFIERS
-- Performing Test HPX_WITH_CXX_FLAG_WNO_IGNORED_QUALIFIERS - Success
-- Performing Test HPX_WITH_CXX_FLAG_WFORMAT_2
-- Performing Test HPX_WITH_CXX_FLAG_WFORMAT_2 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_FORMAT_NONLITERAL
-- Performing Test HPX_WITH_CXX_FLAG_WNO_FORMAT_NONLITERAL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WINIT_SELF
-- Performing Test HPX_WITH_CXX_FLAG_WINIT_SELF - Success
-- Performing Test HPX_WITH_CXX_FLAG_WDOUBLE_PROMOTION
-- Performing Test HPX_WITH_CXX_FLAG_WDOUBLE_PROMOTION - Failed
-- "-Wdouble-promotion" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_QUAL
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_QUAL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_TRAMPOLINES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_TRAMPOLINES - Failed
-- "-Werror=trampolines" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_PARENTHESES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_PARENTHESES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_REORDER
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_REORDER - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_RETURN_TYPE
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_RETURN_TYPE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SEQUENCE_POINT
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SEQUENCE_POINT - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_FORMAT
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_FORMAT - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_MISSING_BRACES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_MISSING_BRACES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SIGN_COMPARE
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SIGN_COMPARE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_CXX_FLAG_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HPX_WITH_C_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_C_FLAG_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HPX_WITH_Fortran_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_Fortran_FLAG_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_VLA
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_VLA - Success
-- Performing Test HPX_WITH_C_FLAG_WERROR_RETURN_TYPE
-- Performing Test HPX_WITH_C_FLAG_WERROR_RETURN_TYPE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SYNC_NAND
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SYNC_NAND - Failed
-- "-Wno-sync-nand" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_WNO_SYNC_NAND
-- Performing Test HPX_WITH_C_FLAG_WNO_SYNC_NAND - Failed
-- "-Wno-sync-nand" not available for language C.
-- Performing Test WITH_LINKER_FLAG_WL__Z_DEFS
-- Performing Test WITH_LINKER_FLAG_WL__Z_DEFS - Success
-- Performing Test HPX_WITH_RDTSC - Success
-- Performing Test HPX_WITH_RDTSCP - Success
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   context
--   random
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Found TCMalloc: /usr/lib/libtcmalloc_minimal.so  
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CFREE
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CFREE - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CFREE
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CFREE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_PVALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_PVALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_PVALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_PVALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_FREE
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_FREE - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_FREE
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_FREE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_REALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_REALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_REALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_REALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_VALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_VALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_VALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_VALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MEMALIGN
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MEMALIGN - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MEMALIGN
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MEMALIGN - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_POSIX_MEMALIGN
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_POSIX_MEMALIGN - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_POSIX_MEMALIGN
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_POSIX_MEMALIGN - Success
-- Using tcmalloc allocator.
-- Found Hwloc: /usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Found Git: /usr/bin/git (found version "2.0.0") 
-- GIT commit is 0dee1c0610509ae966475fc3bcee5f0e3eb1f051.
-- Found PAPI: /opt/papi/5.4.0-release/lib/libpapi.so  
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Found unsuitable Qt version "" from NOTFOUND
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Could NOT find OrangeFS (missing:  ORANGEFS_LIBRARY ORANGEFS_INCLUDE_DIR) 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Could NOT find QThreads (missing:  QTHREADS_LIBRARY QTHREADS_INCLUDE_DIR) 
-- Could NOT find TBBmalloc (missing:  TBB_LIBRARY TBB_PROXY_LIBRARY TBB_INCLUDE_DIR) 
-- Could NOT find SWARM (missing:  SWARM_LIBRARY SWARM_INCLUDE_DIR) 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 

HPX will be installed to /home/pagrubel/build/hpx_buildrelease_clang

---

for inncabs:

cmake -DHPX_ROOT=~/build/hpx_buildrelease_clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_C_COMPILER=clang \
    -DINNCABS_USE_HPX_FUTURIZED=ON \
    -DHPX_DIR=~/build/hpx_buildrelease_clang/lib/cmake/hpx \
    ~/hpx-inncabs

gives:

-- The CXX compiler identification is Clang 3.4.2
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The C compiler identification is Clang 3.4.2
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at /home/pagrubel/hpx/cmake/HPX_Message.cmake:43 (message):
  ERROR: Compilers do not match.  In order to compile HPX application it is
  recommended to use the same compiler as you did for HPX.
  HPX_CXX_COMPILER=/usr/bin/c++, CMAKE_CXX_COMPILER=/usr/bin/clang++.  To
  disable this message set HPX_IGNORE_COMPILER_COMPATIBILITY to On.
Call Stack (most recent call first):
  /home/pagrubel/build/hpx_buildrelease/lib/cmake/HPX/HPXMacros.cmake:15 (hpx_error)
  /home/pagrubel/build/hpx_buildrelease/lib/cmake/HPX/HPXConfig.cmake:52 (hpx_check_compiler_compatibility)
  CMakeLists.txt:32 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by AntonBikineev** [comment]
Can you try removing CMakeCache.txt or even better your build directory and run CMake again (if you haven't tried yet)?

**Comment by pagrubel** [comment]
yes I did that, I also tried make install for hpx as suggested by heller

**Comment by pagrubel** [comment]
Its overriding the compiler that I specified
@K-ballo  @heller @AntonBikineev @hkaiser 

I have double checked everything and @parsa looked over it with me

**Comment by pagrubel** [comment]
cmake -DHPX_ROOT=~/build/hpx_buildrelease_clang \
-DCMAKE_CXX_COMPILER=clang++ \
-DINNCABS_USE_HPX_FUTURIZED=ON \
-DHPX_DIR=~/build/hpx_buildrelease_clang/lib/cmake/hpx \
~/hpx-inncabs

The above should have HPX not hpx which sent a wrong search for the library :
-DHPX_DIR=~/build/hpx_buildrelease_clang/lib/cmake/HPX \

**Comment by pagrubel** [comment]
I'll check this out and make sure before I close it

**Comment by pagrubel** [comment]
Seems to have solved the problem
