### ISSUE TITLE
Reset performance counters between samples

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/inncabs#4]
Since the samples are all run as one run of the application, it would be nice to have the option of resetting performance counters between runs.  (And yes @hkaiser,  we could use the total counts to average them but that doesn't give any information about the variance of them.) I like information even if I don't always report it!

**Comment by hkaiser** [comment]
@pagrubel This should have been fixed by c70cceb680d19d5f78558984106b963391240932, please verify

**Comment by pagrubel** [comment]
It seems to work okay but there is something wrong with the timed counters.

**Comment by pagrubel** [comment]
It seems to work but there are some problems with timed counters. This does not work for the timed counters.

**Comment by pagrubel** [comment]
This was fixed in hpx
